{{- if .Values.operator.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "frkr.fullname" . }}-operator
  labels:
    {{- include "frkr.labels" . | nindent 4 }}
    app.kubernetes.io/component: operator
spec:
  replicas: {{ .Values.operator.replicaCount }}
  selector:
    matchLabels:
      {{- include "frkr.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: operator
  template:
    metadata:
      labels:
        {{- include "frkr.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: operator
    spec:
      serviceAccountName: {{ include "frkr.fullname" . }}-operator
      initContainers:
      - name: copy-migrations
        image: "alpine:3"
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c", "cp -L /raw-migrations/* /migrations/"]
        volumeMounts:
        - name: raw-migrations
          mountPath: /raw-migrations
        - name: migrations
          mountPath: /migrations
      containers:
      - name: operator
        image: "{{ .Values.global.imageRegistry }}{{ .Values.operator.image.repository }}:{{ .Values.operator.image.tag }}"
        imagePullPolicy: {{ .Values.operator.image.pullPolicy }}
        resources:
          {{- toYaml .Values.operator.resources | nindent 10 }}
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        workingDir: /migrations
        volumeMounts:
        - name: migrations
          mountPath: /migrations
      volumes:
      - name: raw-migrations
        configMap:
          name: {{ include "frkr.fullname" . }}-migrations
      - name: migrations
        emptyDir: {}
{{- end }}

