# Full stack values - includes CockroachDB and Redpanda
# Use this for quick start or development

dev:
  enabled: true

dataPlane:
  mode: full
  postgres:
    type: "postgres"

# Provision infrastructure for quickstart/dev
infrastructure:
  cockroachdb:
    provision: false
  postgres:
    provision: true
  redpanda:
    provision: true

