apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: frkr-cockroachdb
  labels:
    app.kubernetes.io/name: cockroachdb
    app.kubernetes.io/instance: frkr
spec:
  serviceName: "frkr-cockroachdb"
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cockroachdb
      app.kubernetes.io/instance: frkr
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cockroachdb
        app.kubernetes.io/instance: frkr
    spec:
      containers:
      - name: cockroachdb
        image: cockroachdb/cockroach:v23.1.10
        imagePullPolicy: IfNotPresent
        command:
          - "/cockroach/cockroach"
          - "start-single-node"
          - "--insecure"
          - "--http-addr=0.0.0.0:8080"
          - "--listen-addr=0.0.0.0:26257"
        ports:
        - containerPort: 26257
          name: grpc
        - containerPort: 8080
          name: http
        volumeMounts:
        - name: datadir
          mountPath: /cockroach/cockroach-data
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
