{{- if .Values.streamingGateway.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "frkr.fullname" . }}-streaming-gateway
  labels:
    {{- include "frkr.labels" . | nindent 4 }}
    app.kubernetes.io/component: streaming-gateway
spec:
  replicas: {{ .Values.streamingGateway.replicaCount }}
  selector:
    matchLabels:
      {{- include "frkr.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: streaming-gateway
  template:
    metadata:
      labels:
        {{- include "frkr.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: streaming-gateway
    spec:
      containers:
      - name: streaming-gateway
        image: "{{ .Values.global.imageRegistry }}{{ .Values.streamingGateway.image.repository }}:{{ .Values.streamingGateway.image.tag }}"
        imagePullPolicy: {{ .Values.streamingGateway.image.pullPolicy }}
        ports:
        - name: grpc
          containerPort: 8081
          protocol: TCP
        env:
        - name: HTTP_PORT
          value: "8081"
        - name: AUTH_TYPE
          value: "{{ .Values.auth.type }}"
        - name: DB_URL
          value: "postgres://{{ .Values.dataPlane.db.user }}:{{ .Values.dataPlane.db.password }}@{{ .Values.dataPlane.db.host }}:{{ .Values.dataPlane.db.port }}/{{ .Values.dataPlane.db.database }}?sslmode={{ .Values.dataPlane.db.sslMode }}"
        {{- if .Values.dataPlane.db.password }}
        - name: DB_PASSWORD
          value: {{ .Values.dataPlane.db.password | quote }}
        {{- else if .Values.dataPlane.db.passwordRef }}
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.dataPlane.db.passwordRef }}
              key: password
        {{- end }}
        - name: BROKER_URL
          value: "{{ join "," .Values.dataPlane.broker.brokers }}"
        resources:
          {{- toYaml .Values.streamingGateway.resources | nindent 10 }}
        livenessProbe:
          grpc:
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          grpc:
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 5
{{- end }}

