{{- if .Values.streamingGateway.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "frkr.fullname" . }}-streaming-gateway
  labels:
    {{- include "frkr.labels" . | nindent 4 }}
    app.kubernetes.io/component: streaming-gateway
spec:
  type: ClusterIP
  ports:
  - port: 8081
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "frkr.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: streaming-gateway
{{- end }}

