{{- if .Values.ingestGateway.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "frkr.fullname" . }}-ingest-gateway
  labels:
    {{- include "frkr.labels" . | nindent 4 }}
    app.kubernetes.io/component: ingest-gateway
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "frkr.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ingest-gateway
{{- end }}

