apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: frkr-redpanda
  labels:
    app.kubernetes.io/name: redpanda
    app.kubernetes.io/instance: frkr
spec:
  serviceName: "frkr-redpanda"
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: redpanda
      app.kubernetes.io/instance: frkr
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redpanda
        app.kubernetes.io/instance: frkr
    spec:
      containers:
      - name: redpanda
        image: docker.redpanda.com/redpandadata/redpanda:v23.2.14
        command:
        - rpk
        - redpanda
        - start
        - --smp
        - "1"
        - --reserve-memory
        - 0M
        - --overprovisioned
        - --check=false
        - --kafka-addr
        - PLAINTEXT://0.0.0.0:9092,OUTSIDE://0.0.0.0:9094
        - --advertise-kafka-addr
        - PLAINTEXT://frkr-redpanda:9092,OUTSIDE://localhost:9094
        # Default entrypoint (using args if any)
        ports:
        - containerPort: 9092
          name: kafka
        - containerPort: 9644
          name: admin
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
